### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by TheDuriel** [TheFutureGadgetsLab/WaifuXL#164]
After following the provided instructions for locally running waifuxl, and even trying out the specific commit mentioned on the web version, I get the following error when trying to open the site under localhost/3000:

```
Duriel@KonpyutaChan MINGW64 /d/Projects/AWaifuGenerator/WaifuXL ((f5c9352...))
$ npm run dev

> dev
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> [PWA] PWA support is disabled
> [PWA] PWA support is disabled
error - unable to locate 'D:\Projects\AWaifuGenerator\WaifuXL\node_modules\onnxruntime-web\dist\*.wasm' glob
wait  - compiling / (client and server)...
error - unable to locate 'D:\Projects\AWaifuGenerator\WaifuXL\node_modules\onnxruntime-web\dist\*.wasm' glob
wait  - compiling /_error (client and server)...
error - unable to locate 'D:\Projects\AWaifuGenerator\WaifuXL\node_modules\onnxruntime-web\dist\*.wasm' glob
error - Error: Cannot find module 'D:\Projects\AWaifuGenerator\WaifuXL\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\utils.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\cli\next-dev.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\lib\commands.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponentsImpl [as loadDefaultErrorComponents] (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js:23:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\dev\next-dev-server.js:1196:43)
    at async DevServer.renderErrorToResponseImpl (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:1308:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\build\\utils.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\bin\\next'
  ]
}
Error: Cannot find module 'D:\Projects\AWaifuGenerator\WaifuXL\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\utils.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\cli\next-dev.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\lib\commands.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponentsImpl [as loadDefaultErrorComponents] (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js:23:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\dev\next-dev-server.js:1196:43)
    at async DevServer.renderErrorToResponseImpl (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:1308:40)
    at async pipe.req.req (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:1192:30)
    at async DevServer.pipeImpl (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:458:25)
    at async DevServer.run (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\dev\next-dev-server.js:839:28)
    at async DevServer.handleRequestImpl (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:375:20)
    at async D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:157:99 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\build\\utils.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\bin\\next'
  ]
}
```

Web stuff isn't my forte, so this has me stumped.

Unrelated: Really loving the model! I actually use it a lot and was hoping to speed things up.

**Comment by haydn-jones** [comment]
Try running master now. We just rewrote the website. We're also going to add PyTorch support so inference should be *much* faster there. Stay tuned for that.

**Comment by TheDuriel** [comment]
```
$ npm run dev

> dev
> next

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> [PWA] PWA support is disabled
> [PWA] PWA support is disabled
error - unable to locate 'D:\Projects\AWaifuGenerator\WaifuXL\node_modules\onnxruntime-web\dist\*.wasm' glob
wait  - compiling /_error (client and server)...
<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\loaders\css-loader\src\index.js??ruleSet[1].rules[2].oneOf[7].use[1]!D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\loaders\postcss-loader\src\index.js??ruleSet[1].rules[2].oneOf[7].use[2]!D:\Projects\AWaifuGenerator\WaifuXL\node_modules\tailwindcss\tailwind.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 3 items } -> webpack/lib/ModuleWarning -> Warning
error - unable to locate 'D:\Projects\AWaifuGenerator\WaifuXL\node_modules\onnxruntime-web\dist\*.wasm' glob
error - Error: Cannot find module 'D:\Projects\AWaifuGenerator\WaifuXL\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\next-server.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\next.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\lib\start-server.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\cli\next-dev.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\lib\commands.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\dev\next-dev-server.js:1008:43)
    at async DevServer.renderErrorToResponse (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:1111:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\bin\\next'
  ]
}
Error: Cannot find module 'D:\Projects\AWaifuGenerator\WaifuXL\.next\fallback-build-manifest.json'
Require stack:
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\next-server.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\next.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\lib\start-server.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\cli\next-dev.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\lib\commands.js
- D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\bin\next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.mod._resolveFilename (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\build\webpack\require-hook.js:27:32)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.loadDefaultErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\load-components.js:22:24)
    at DevServer.getFallbackErrorComponents (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\dev\next-dev-server.js:1008:43)
    at async DevServer.renderErrorToResponse (D:\Projects\AWaifuGenerator\WaifuXL\node_modules\next\dist\server\base-server.js:1111:40) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\load-components.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\next-server.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\next.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\server\\lib\\start-server.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\cli\\next-dev.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\lib\\commands.js',
    'D:\\Projects\\AWaifuGenerator\\WaifuXL\\node_modules\\next\\dist\\bin\\next'
  ]
}

```

On #cfe1c5c

Rather odd. I'd love to say the problem is mine. The only thing I see here are missing npm modules. o.0

npm installation did complete with warnings, but only in so far as outdated modules goes. Which aren't the ones here indicated as missing anyways.

Awesome rewrite though! Web version is now doing in seconds what almost took minutes before!

**Comment by haydn-jones** [comment]
Closing this, if you're looking for speeding things up watch the GPU compatibility issue.
